version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./app/:/var/www/app/
    ports:
      - '8001:80'
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - ./app/:/var/www/app/
    networks:
      - app-network

  mysql:
    image: mysql
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: api_rest_project_db
      MYSQL_USER: 'user'
      MYSQL_USER_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network: